### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by motchang** [motchang/sandbox#2]
- [ ] #1 [タスク](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/1)
- [ ] #2 [開催日に必要な備品](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/2)
- [ ] #3 [twitterや、サイトで使えるロゴ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/3)
- [ ] #4 [ボランティアスタッフスレ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/4)
- [ ] #5 [サイトにハッシュタグなどを記載する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/5)
- [ ] #6 [「YAPCとは？」というテキストを書く](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/6)
- [ ] #7 [オーディエンス応募フォーム作る](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/7)
- [ ] #8 [主催のとこ追記](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/8)
- [ ] #9 [MS社員様（紙製）に持っていただく通行止めサイン](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/9)
- [ ] #10 [fix typo](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/10)
- [ ] #11 [懇親会](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/11)
- [ ] #12 [掲示物](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/12)
- [ ] #13 [タイムテーブル作成](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/13)
- [ ] #14 [道案内コンテンツ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/14)
- [ ] #15 [写真](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/15)
- [ ] #16 [録画](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/16)
- [ ] #17 [ボランティアスタッフ確定](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/17)
- [ ] #18 [当日用スマホ向けポータルサイト](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/18)
- [ ] #19 [サイトをJekyllあたりで作り直す](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/19)
- [ ] #20 [to be jekyll](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/20)
- [ ] #21 [サイトにソーシャル系のボタンを設置する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/21)
- [ ] #22 [GHpages で_postsが無視されている](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/22)
- [ ] #23 [チャットを用意する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/23)
- [ ] #24 [ベストトーク賞を作る](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/24)
- [ ] #25 [6/4 打ち合わせスレ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/25)
- [ ] #26 [トーク採択](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/26)
- [ ] #27 [フロアマップ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/27)
- [ ] #28 [買った物スレ（メモ）](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/28)
- [ ] #29 [参加応募ページ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/29)
- [ ] #30 [インターネット担当者決める](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/30)
- [ ] #31 [会場諸注意](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/31)
- [ ] #32 [スタッフ担当箇所リスト](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/32)
- [ ] #33 [受付担当者を決める](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/33)
- [ ] #34 [スタッフ緊急連絡網（電話）](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/34)
- [ ] #35 [スタッフ識別章を考える](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/35)
- [ ] #36 [飛び入りトラック](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/36)
- [ ] #37 [ページにソーシャルボタンの設置](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/37)
- [ ] #38 [「スタッフのしおり」をつくる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/38)
- [ ] #39 [部屋担当心得](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/39)
- [ ] #40 [エントランス入館受付心得](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/40)
- [ ] #41 [ネット担当心得](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/41)
- [ ] #42 [遊撃隊の心得](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/42)
- [ ] #43 [不適切とは](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/43)
- [ ] #44 [スピーカーに通知する事柄をまとめる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/44)
- [ ] #45 [2日目の打ち上げ的なパーリーナイト](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/45)
- [ ] #46 [スタッフ用のしおり作成](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/46)
- [ ] #47 [設営作業](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/47)
- [ ] #48 [撤収手順をまとめる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/48)
- [ ] #49 [サイト：トーク募集中をクローズする](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/49)
- [ ] #50 [当日トラック（仮）の説明ページ作る](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/50)
- [ ] #51 [リポジトリの内容を明確にするため説明を追記](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/51)
- [ ] #52 [Chage to related path](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/52)
- [ ] #53 [タイムテーブルの方に「決定」ラベルが欲しい](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/53)
- [ ] #54 [fix link](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/54)
- [ ] #55 [飛び入りトラック書いた](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/55)
- [ ] #56 [飛び入りトラックのお知らせ記事書いた](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/56)
- [ ] #57 [Connpassのメッセージ機能経由で言うタスク](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/57)
- [ ] #58 [登壇者が参加登録わすれていないかチェックする](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/58)
- [ ] #59 [タイムキーパーは機械にやらせるぞ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/59)
- [ ] #60 [ボランティアスタッフ打合＆キックオフ懇親会 No2](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/60)
- [ ] #61 [宴会大臣の募集](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/61)
- [ ] #62 [銅鑼についてのエントリーを書いてみた](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/62)
- [ ] #63 [タイムテーブルにLTのリストをのっける](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/63)
- [ ] #64 [ステッカー用のロゴの制作](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/64)
- [ ] #65 [トーク予定のあるスタッフのシフト調整](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/65)
- [ ] #66 [Macだと4:3になる事があるので、設定方法を追記する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/66)
- [ ] #67 [周辺の店をサイトに追記しておく](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/67)
- [ ] #68 [ビデオカメラ用の延長ケーブルを買う](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/68)
- [ ] #69 [懇親会関連でツイートの必要なタスク](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/69)
- [ ] #70 [懇親会の受付と誘導について考える](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/70)
- [ ] #71 [LTで日付移動依頼がきたので調整](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/71)
- [ ] #72 [自動タイムスケジュール告知ボットをつくる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/72)
- [ ] #73 [飛び入りトラックの情報をアップデート](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/73)
- [ ] #74 [飛び入りトラックのリンクを修正しました](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/74)
- [ ] #75 [アサインがされていないスタッフさんに人力個別連絡](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/75)
- [ ] #76 [リンクバックエントリを書く](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/76)
- [ ] #77 [Connpass抽選が完了したら即刻CSVを保存し、キャンセルでの補欠登録をブロックする](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/77)
- [ ] #78 [前日準備](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/78)
- [ ] #79 [LT運営手順書](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/79)
- [ ] #80 [最初のアナウンス文](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/80)
- [ ] #81 [昼食、弁当を注文したい方スレ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/81)
- [ ] #82 [LT鳴り物についての記事](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/82)
- [ ] #83 [画像のリンク先間違えてた！](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/83)
- [ ] #84 [拡張子間違えてた！](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/84)
- [ ] #85 [前日にまいんだーさんともくもく作業配信](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/85)
- [ ] #86 [トークに投票しようエントリを書く](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/86)
- [ ] #87 [各所リーダーにおたのみ申す事](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/87)
- [ ] #88 [懇親会キャンセルがのびているのでつらい](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/88)
- [ ] #89 [7/3(日)懇親会、参加者が伸びたので店に連絡](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/89)
- [ ] #90 [動画公開不可や、ヤバそうなのを集める](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/90)
- [ ] #91 [落し物を再度アナウンス](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/91)
- [ ] #92 [写真選定](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/92)
- [ ] #93 [動画公開](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/93)
- [ ] #94 [動画公開順考える](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/94)
- [ ] #95 [ブログリンク](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/95)
- [ ] #96 [クローズエントリ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/96)
- [ ] #97 [「こうしたらよかった」、「これはよかった」報告スレ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/97)
- [ ] #98 [公式系まとめ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/98)
- [ ] #99 [登壇者スライドまとめ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/99)
- [ ] #100 [感想エントリまとめ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/100)
- [ ] #101 [トップなどをクローズ状態に変更](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/101)
- [ ] #102 [スライド公開したなら、募集ISSUEに追記してくださいと告知する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/102)
- [ ] #103 [投票サイトを落とす](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/103)
- [ ] #104 [Periscopeの評判を知りたい](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/104)
- [ ] #105 [ドタキャンになったLTをリストアップし、ラベルを剥がす](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/105)
- [ ] #106 [Connpassのメッセージでフォローアップ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/106)
- [ ] #107 [今回のSlack運用ノウハウをどこかにまとめる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/107)
- [ ] #108 [今回の質問方式はなかなか難しかったらしいけん](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/108)
- [ ] #109 [投票君](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/109)
- [ ] #110 [忘れ物を解決する](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/110)
- [ ] #111 [Add ravelll's blog entries](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/111)
- [ ] #112 [動画のコツをまとめる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/112)
- [ ] #113 [当日の写真をzipか何かに固めてアップロードする](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/113)
- [ ] #114 [終わる前に用意しておいたほうがよかったものや、すぐやるべきもの](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/114)
- [ ] #115 [サイトのアクセスについて（メモ](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/115)
- [ ] #116 [TT生成とかにつかったしょうもないツールをどっかに上げる](https://api.github.com/repos/hachiojipm/yapcasia-8oji-2016mid/issues/116)
